// <auto-generated />
using System;
using CoffeeShopApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShopApp.Migrations
{
    [DbContext(typeof(CoffeeShopDbContext))]
    [Migration("20260523185110_AddOrderPaymentMethod")]
    partial class AddOrderPaymentMethod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShopApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "Assets/Products/Капучино.png",
                            Name = "Кава"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "Assets/Products/Какао.png",
                            Name = "Гарячі напої"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "Assets/Products/Сендвіч з куркою.png",
                            Name = "Сендвічі та перекуси"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "Assets/Products/Круасан.png",
                            Name = "Випічка"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "Assets/Products/Чізкейк.png",
                            Name = "Десерти"
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "Assets/Products/Колд брю.png",
                            Name = "Холодні напої"
                        });
                });

            modelBuilder.Entity("CoffeeShopApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeeShopApp.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CoffeeShopApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Класичний міцний еспресо",
                            ImagePath = "Assets/Products/Еспресо.png",
                            IsAvailable = true,
                            Name = "Еспресо",
                            Price = 25m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Подвійний еспресо",
                            ImagePath = "Assets/Products/Допіо.png",
                            IsAvailable = true,
                            Name = "Допіо",
                            Price = 35m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Еспресо з гарячою водою",
                            ImagePath = "Assets/Products/Американо.png",
                            IsAvailable = true,
                            Name = "Американо",
                            Price = 30m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Еспресо з молоком та пінкою",
                            ImagePath = "Assets/Products/Капучино.png",
                            IsAvailable = true,
                            Name = "Капучино",
                            Price = 40m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ніжна кава з молоком",
                            ImagePath = "Assets/Products/Лате.png",
                            IsAvailable = true,
                            Name = "Лате",
                            Price = 45m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Подвійний еспресо з молоком",
                            ImagePath = "Assets/Products/Флет вайт.png",
                            IsAvailable = true,
                            Name = "Флет вайт",
                            Price = 50m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кава з вершками та ваніллю",
                            ImagePath = "Assets/Products/Раф.png",
                            IsAvailable = true,
                            Name = "Раф",
                            Price = 55m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кава з шоколадом",
                            ImagePath = "Assets/Products/Мокачино.png",
                            IsAvailable = true,
                            Name = "Мокачино",
                            Price = 55m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Еспресо з молочною пінкою",
                            ImagePath = "Assets/Products/Макіато.png",
                            IsAvailable = true,
                            Name = "Макіато",
                            Price = 42m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Лате з карамельним сиропом",
                            ImagePath = "Assets/Products/Карамельний лате.png",
                            IsAvailable = true,
                            Name = "Карамельний лате",
                            Price = 62m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Чорна кава ручного заварювання",
                            ImagePath = "Assets/Products/Фільтр кава.png",
                            IsAvailable = true,
                            Name = "Фільтр кава",
                            Price = 48m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Чорний чай",
                            ImagePath = "Assets/Products/Чорний чай.png",
                            IsAvailable = true,
                            Name = "Чорний чай",
                            Price = 30m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Гаряче какао з молоком",
                            ImagePath = "Assets/Products/Какао.png",
                            IsAvailable = true,
                            Name = "Какао",
                            Price = 48m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Китайський зелений чай",
                            ImagePath = "Assets/Products/Зелений чай.png",
                            IsAvailable = true,
                            Name = "Зелений чай",
                            Price = 35m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кава холодного заварювання",
                            ImagePath = "Assets/Products/Колд брю.png",
                            IsAvailable = true,
                            Name = "Колд брю",
                            Price = 55m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Еспресо з тоніком",
                            ImagePath = "Assets/Products/Еспресо тонік.png",
                            IsAvailable = true,
                            Name = "Еспресо тонік",
                            Price = 65m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Холодне лате з льодом",
                            ImagePath = "Assets/Products/Айс лате.png",
                            IsAvailable = true,
                            Name = "Айс лате",
                            Price = 55m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Домашній лимонад",
                            ImagePath = "Assets/Products/Лимонад.png",
                            IsAvailable = true,
                            Name = "Лимонад",
                            Price = 45m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Свіжовижатий сік",
                            ImagePath = "Assets/Products/Апельсиновий фреш.png",
                            IsAvailable = true,
                            Name = "Апельсиновий фреш",
                            Price = 60m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Холодна матча з молоком",
                            ImagePath = "Assets/Products/Айс матча лате.png",
                            IsAvailable = true,
                            Name = "Айс матча лате",
                            Price = 68m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Курка, сир, овочі",
                            ImagePath = "Assets/Products/Сендвіч з куркою.png",
                            IsAvailable = true,
                            Name = "Сендвіч з куркою",
                            Price = 85m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Теплий сендвіч",
                            ImagePath = "Assets/Products/Паніні з шинкою.png",
                            IsAvailable = true,
                            Name = "Паніні з шинкою",
                            Price = 90m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Тост з авокадо та яйцем",
                            ImagePath = "Assets/Products/Тост з авокадо.png",
                            IsAvailable = true,
                            Name = "Тост з авокадо",
                            Price = 110m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Бейгл з крем-сиром та лососем",
                            ImagePath = "Assets/Products/Бейгл з лососем.png",
                            IsAvailable = true,
                            Name = "Бейгл з лососем",
                            Price = 135m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Рол з овочами та соусом",
                            ImagePath = "Assets/Products/Овочевий рол.png",
                            IsAvailable = true,
                            Name = "Овочевий рол",
                            Price = 82m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Тости з томатами та сиром",
                            ImagePath = "Assets/Products/Брускета.png",
                            IsAvailable = true,
                            Name = "Брускета",
                            Price = 78m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Французький круасан",
                            ImagePath = "Assets/Products/Круасан.png",
                            IsAvailable = true,
                            Name = "Круасан",
                            Price = 35m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Круасан з шоколадною начинкою",
                            ImagePath = "Assets/Products/Круасан з шоколадом.png",
                            IsAvailable = true,
                            Name = "Круасан з шоколадом",
                            Price = 45m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ароматна булочка",
                            ImagePath = "Assets/Products/Сінабон.png",
                            IsAvailable = true,
                            Name = "Сінабон",
                            Price = 42m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Шоколадний маффін",
                            ImagePath = "Assets/Products/Маффін шоколадний.png",
                            IsAvailable = true,
                            Name = "Маффін шоколадний",
                            Price = 38m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Круасан з мигдалевим кремом",
                            ImagePath = "Assets/Products/Мигдалевий круасан.png",
                            IsAvailable = true,
                            Name = "Мигдалевий круасан",
                            Price = 58m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Солодка випічка з бананом",
                            ImagePath = "Assets/Products/Банановий хліб.png",
                            IsAvailable = true,
                            Name = "Банановий хліб",
                            Price = 52m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Класичний чізкейк",
                            ImagePath = "Assets/Products/Чізкейк.png",
                            IsAvailable = true,
                            Name = "Чізкейк",
                            Price = 75m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Італійський десерт",
                            ImagePath = "Assets/Products/Тірамісу.png",
                            IsAvailable = true,
                            Name = "Тірамісу",
                            Price = 80m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Шоколадний десерт",
                            ImagePath = "Assets/Products/Брауні.png",
                            IsAvailable = true,
                            Name = "Брауні",
                            Price = 60m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Домашній медовий торт",
                            ImagePath = "Assets/Products/Медівник.png",
                            IsAvailable = true,
                            Name = "Медівник",
                            Price = 70m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Еклер із заварним кремом",
                            ImagePath = "Assets/Products/Еклер.png",
                            IsAvailable = true,
                            Name = "Еклер",
                            Price = 62m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Набір мигдалевого печива",
                            ImagePath = "Assets/Products/Макаронс.png",
                            IsAvailable = true,
                            Name = "Макаронс",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("CoffeeShopApp.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Адміністратор",
                            IsActive = true,
                            Password = "admin123",
                            Role = "Адміністратор",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Касир",
                            IsActive = true,
                            Password = "cashier123",
                            Role = "Касир",
                            Username = "cashier"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Менеджер",
                            IsActive = true,
                            Password = "manager123",
                            Role = "Менеджер",
                            Username = "manager"
                        });
                });

            modelBuilder.Entity("CoffeeShopApp.Models.OrderItem", b =>
                {
                    b.HasOne("CoffeeShopApp.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopApp.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CoffeeShopApp.Models.Product", b =>
                {
                    b.HasOne("CoffeeShopApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoffeeShopApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CoffeeShopApp.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CoffeeShopApp.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
